import type { Staff } from "./types.js";

/** Roster from 2026 RN ROTATION.xlsx (August sheet) — Rotation Engine v5. */
export function seedRoster(): Staff[] {
  const s = (id: string, name: string, agency: boolean): Staff => ({
    id,
    name,
    role: "nurse",
    competency: "trained",
    tech_specialty: null,
    avoidNight: false,
    agency,
    active: true,
    pickedUp: false,
    predetermined: null,
  });
  return [
    s("S001", "Achs, Marlena", false),
    s("S002", "Alexander, Rachel", false),
    s("S003", "Alston, Amia", false),
    s("S004", "Avers, Kaylin", false),
    s("S005", "Barker, Brad", false),
    s("S006", "Barrett, Chad", false),
    s("S007", "Bebko, Madelyn", false),
    s("S008", "Beckman, Sara", false),
    s("S009", "Blackwood, Sydney", false),
    s("S010", "Bostelman, Emily", false),
    s("S011", "Brooks, Amber", false),
    s("S012", "Buckalew, Anna", false),
    s("S013", "Burnside, Jennifer", false),
    s("S014", "Carmean, Sandy", true),
    s("S015", "Carson, Elliana", false),
    s("S016", "Christman, Natalie", false),
    s("S017", "Clark, Brandon", false),
    s("S018", "Cline, Brittany", false),
    s("S019", "Clinger, Autumn", false),
    s("S020", "Colston, Tyler", false),
    s("S021", "Colvin, Emily", false),
    s("S022", "Combs, Jessie", false),
    s("S023", "Cooper, Samantha", false),
    s("S024", "Cornelius, Brookeann", false),
    s("S025", "Cornwell, Alex", false),
    s("S026", "Cramer, Anthony", false),
    s("S027", "Crafton, Jennifer", false),
    s("S028", "Culbreath, Katie (KC)", false),
    s("S029", "Culver, Victoria", false),
    s("S030", "Dawson, Gabe", false),
    s("S031", "Delamater, Michelle", false),
    s("S032", "Depew, Jacquelyn", false),
    s("S033", "Doepel, Megan", false),
    s("S034", "Drake, Kyrsten", false),
    s("S035", "Drew, Amy", false),
    s("S036", "Dues, Nicholas", false),
    s("S037", "Everidge, Lindsey", false),
    s("S038", "Ewing, Lauren", false),
    s("S039", "Eyler, Allison", false),
    s("S040", "Fennell, McKenzie", false),
    s("S041", "Fiegly, Amberly", false),
    s("S042", "Fife, Taylor", false),
    s("S043", "Flavin, Madeline", false),
    s("S044", "Fletcher, Julie", false),
    s("S045", "Fletcher, Taylor", false),
    s("S046", "Freitag, Marla", false),
    s("S047", "Gaines, Joshua", false),
    s("S048", "Gates, Tyler", false),
    s("S049", "Gayles, Charity", false),
    s("S050", "Gebby, Joslyn", false),
    s("S051", "Gillespie, Alison", false),
    s("S052", "Godfrey, Karleigh", false),
    s("S053", "Goecke, Stacey", false),
    s("S054", "Goetz, Taylor", false),
    s("S055", "Griggs, Ty-Asia", false),
    s("S056", "Harris, Eric", true),
    s("S057", "Hawkins, Talisha", false),
    s("S058", "Hogan, Missy", false),
    s("S059", "Hull, Christina", false),
    s("S060", "Jennings, Cindy", false),
    s("S061", "Johnson, Kaylie", false),
    s("S062", "Johnson, Lauren", false),
    s("S063", "Jones, Brooke", false),
    s("S064", "Kelley, Alivia", false),
    s("S065", "King, Shannon", false),
    s("S066", "Klemmensen, Noah", false),
    s("S067", "Kline, Heather", false),
    s("S068", "Kozee, Alyssa", false),
    s("S069", "LaFrance, Jackie", false),
    s("S070", "Lamb, Stacey", false),
    s("S071", "Land, Americus", false),
    s("S072", "Langston, Shelly", false),
    s("S073", "Lemp, Reaghan", false),
    s("S074", "Lingaas, Jessica", false),
    s("S075", "Lowe, Taylor", false),
    s("S076", "Lugenbeel, Klarissa", false),
    s("S077", "Lutz, Dakota", false),
    s("S078", "Mangan, Kimberly", false),
    s("S079", "Martin, Abbie", false),
    s("S080", "Martin, Sara", false),
    s("S081", "Maxwell, McKenzie", false),
    s("S082", "Mazurek, Katelyn", false),
    s("S083", "McBride, Kela", false),
    s("S084", "McCray, Jamie", false),
    s("S085", "McIntosh, Rachael", false),
    s("S086", "Minor, Jordan", false),
    s("S087", "Mohamed, Aisha", true),
    s("S088", "Moman, Bruce", false),
    s("S089", "Murray, Kristina", false),
    s("S090", "Nally, Shannon", false),
    s("S091", "Neace, Mackenzie", false),
    s("S092", "Neikirk, Joanna", false),
    s("S093", "Neuhardt, Tiffani", false),
    s("S094", "Nicely, Alyssa", true),
    s("S095", "Nixon, Elijah", false),
    s("S096", "Oda, Alysha", false),
    s("S097", "Ohl, Shannon", false),
    s("S098", "Pahl, Addison", false),
    s("S099", "Pangilinan, Antonio", false),
    s("S100", "Parks, Tenise", false),
    s("S101", "Parrish, Pam", false),
    s("S102", "Paul, Shaylnn", false),
    s("S103", "Plas, Katelyn", false),
    s("S104", "Pope, Lianna", false),
    s("S105", "Powell, Whitney", false),
    s("S106", "Ramsey, Kat", false),
    s("S107", "Randall, Faith", false),
    s("S108", "Reese, Savanna", false),
    s("S109", "Reiber, Annette", false),
    s("S110", "Ricks, Caleb", false),
    s("S111", "Robinson, Jarred", false),
    s("S112", "Robinson, Samuel", false),
    s("S113", "Rosner, Erica", false),
    s("S114", "Rupert, Jacob", false),
    s("S115", "Schleinitz, Elli", false),
    s("S116", "Schloss-Hall, Suzanne", false),
    s("S117", "Sizemore, Lindsey", false),
    s("S118", "Slabach, Marlaina", false),
    s("S119", "Smith, Makaya", false),
    s("S120", "Snowden, Kim", false),
    s("S121", "Snyder, Abby", false),
    s("S122", "Snyder, Nancy", false),
    s("S123", "Solis, Aaliyah", true),
    s("S124", "Sparks, Nicole", false),
    s("S125", "St. Clair, Penny", false),
    s("S126", "Stewart, Candice", false),
    s("S127", "Stroud, Hannah", false),
    s("S128", "Thomas, Daniel", true),
    s("S129", "Timmerman, Chris", false),
    s("S130", "Timmons, Hannah", false),
    s("S131", "Tomlinson, Hannah", false),
    s("S132", "Trapp, Vanessa", false),
    s("S133", "Turner, Kashia", false),
    s("S134", "Turner, Kaylin", false),
    s("S135", "Van Der Merwe, Megan", false),
    s("S136", "Varner, Kirsten", false),
    s("S137", "Von Dohre, Jane", false),
    s("S138", "Welch, Taylor", false),
    s("S139", "Williams, Christian", false),
    s("S140", "Wilmoth, Julie", false),
    s("S141", "Winbush, Kenyatta", false),
    s("S142", "Woolery, McKenzie", false),
    s("S143", "Zukowitz, Kaylee", false),
  ];
}

